---
- hosts: apache
  become: yes
  tasks:
    - name: Install httpd (apache2)
      yum:
        name: httpd
        state: present

    - name: Firewall config
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - http
        - https

    - name: Start httpd
      systemd:
        name: httpd
        state: started
        enabled: yes


#    - name: apache2 listen on port 8081
#      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
#      notify:
#        - restart apache2
#
#    - name: apache2 virtualhost on port 8081
#      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
#      notify:
#        - restart apache2
#
#  handlers:
#    - name: restart apache2
#      service: name=apache2 state=restarted


