---
- hosts: apache
  become: yes
  tasks:
    - name: Install httpd (apache2)
      yum:
        name: httpd
        state: present

#    - name: Firewall config
#      firewalld:
#        service: "{{ item }}"
#        permanent: yes
#        state: enabled
#      with_items:
#        - http
#        - https

    - name: Start httpd
      systemd:
        name: httpd
        state: started
        enabled: yes


